## Maxtrix Multiplication

In [63]:
import numpy as np
import pandas as pd
import os
import pickle


def makeMatrix():
    np.random.seed(20145128)
    matrix = np.floor(np.random.random(40) * 10)
    for i in range(40):
        if matrix[i] == 0:
            matrix[i] = np.NaN
    return matrix

def savefile(file_path,matrix):
    f = open(file_path,"wb")
    pickle.dump(matrix,f)
    f.close()
    
def loadfile(file_path):
    f = open(file_path,"rb")
    data = pickle.load(f)
    return data

def makeShape(matrix,row,col):
    mat = np.zeros((row,col))
    k = 0
    
    for i in range(0,row):
        for j in range(0,col):
            mat[i][j] = matrix[k]
            k = k + 1
            if k > 40:
                return 0
            
    return mat
        
def nanToZero(matrix):
    for i in range(40):
        matrix[np.isnan(matrix)] = 0
    return matrix
    
def matMul(mat1,mat2):
    matrix = np.zeros((8,8))
    
    for i in range(0,8):
        for j in range(0,8):
            for k in range(0,5):
                temp = mat1[i][k] * mat2[k][j]
                matrix[i][j] = matrix[i][j] + temp
            
    return matrix
    
def makePandas(matrix):
    datas = matrix
    rows = ["1행","2행","3행","4행","5행","6행","7행","8행"]
    columns = ["1열","2열","3열","4열","5열","6열","7열","8열"]
    df = pd.DataFrame(datas, index=rows,columns=columns)
    
    return df

if __name__ == "__main__":
    file_path = os.getcwd() + "/matrix.pkl"
    
    matrix = makeMatrix()
    print(matrix)
    savefile(file_path,matrix)
    
    del matrix
    matrix = loadfile(file_path)
    print(matrix)
    
    matrix = nanToZero(matrix)
    print(matrix)
    
    mat1 = makeShape(matrix,8,5)
    print(mat1)
    mat2 = makeShape(matrix,5,8)
    print(mat2)
    
    result = matMul(mat1,mat2)
    print(result)
    
    frame = makePandas(result)
    display(frame)

[nan  1.  2.  5.  6.  4. nan  1.  4.  6.  7.  6.  6.  3.  8.  6.  1.  4.
  3.  9.  2.  8.  7.  2.  7.  5.  9.  5. nan  2.  7.  7.  2.  5.  3.  7.
  4.  4.  9.  7.]
[nan  1.  2.  5.  6.  4. nan  1.  4.  6.  7.  6.  6.  3.  8.  6.  1.  4.
  3.  9.  2.  8.  7.  2.  7.  5.  9.  5. nan  2.  7.  7.  2.  5.  3.  7.
  4.  4.  9.  7.]
[0. 1. 2. 5. 6. 4. 0. 1. 4. 6. 7. 6. 6. 3. 8. 6. 1. 4. 3. 9. 2. 8. 7. 2.
 7. 5. 9. 5. 0. 2. 7. 7. 2. 5. 3. 7. 4. 4. 9. 7.]
[[0. 1. 2. 5. 6.]
 [4. 0. 1. 4. 6.]
 [7. 6. 6. 3. 8.]
 [6. 1. 4. 3. 9.]
 [2. 8. 7. 2. 7.]
 [5. 9. 5. 0. 2.]
 [7. 7. 2. 5. 3.]
 [7. 4. 4. 9. 7.]]
[[0. 1. 2. 5. 6. 4. 0. 1.]
 [4. 6. 7. 6. 6. 3. 8. 6.]
 [1. 4. 3. 9. 2. 8. 7. 2.]
 [7. 5. 9. 5. 0. 2. 7. 7.]
 [2. 5. 3. 7. 4. 4. 9. 7.]]
[[ 53.  69.  76.  91.  34.  53. 111.  87.]
 [ 41.  58.  65.  91.  50.  56.  89.  76.]
 [ 67. 122. 125. 196. 122. 132. 183. 132.]
 [ 47.  88.  85. 150.  86. 101. 138. 104.]
 [ 67. 123. 120. 180. 102. 120. 190. 127.]
 [ 45.  89.  94. 138. 102.  95. 125.  83.]
 [ 71.  97. 123. 141. 100.  87. 132. 109.]
 [ 97. 127. 156. 189. 102. 118. 186. 151.]]

      1열     2열     3열     4열     5열     6열     7열     8열
1행  53.0   69.0   76.0   91.0   34.0   53.0  111.0   87.0
2행  41.0   58.0   65.0   91.0   50.0   56.0   89.0   76.0
3행  67.0  122.0  125.0  196.0  122.0  132.0  183.0  132.0
4행  47.0   88.0   85.0  150.0   86.0  101.0  138.0  104.0
5행  67.0  123.0  120.0  180.0  102.0  120.0  190.0  127.0
6행  45.0   89.0   94.0  138.0  102.0   95.0  125.0   83.0
7행  71.0   97.0  123.0  141.0  100.0   87.0  132.0  109.0
8행  97.0  127.0  156.0  189.0  102.0  118.0  186.0  151.0